# Reusable composite action for Rust environment setup
# Used by CI workflow to configure Rust toolchain and Tauri dependencies
name: 'Rust Setup'
description: 'Setup Rust toolchain with system dependencies for Tauri'

# Optional input for additional Rust components (e.g., clippy, rustfmt)
inputs:
  components:
    description: 'Additional Rust components to install'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # Install stable Rust toolchain with optional components
    # Uses dtolnay/rust-toolchain for reliable cross-platform installation
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    # Install system libraries required for Tauri builds on Ubuntu
    # - libwebkit2gtk-4.1-dev: WebKit rendering engine
    # - libappindicator3-dev: System tray support
    # - librsvg2-dev: SVG rendering support
    # - patchelf: ELF binary modification for packaging
    - name: Install dependencies (Ubuntu only)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
