name: 'Rust Setup'
description: 'Setup Rust toolchain with system dependencies for Tauri'

inputs:
  components:
    description: 'Additional Rust components to install'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - name: Install system dependencies (Ubuntu)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
